pipelines:
  - name: demo_application #1
    steps:
      - name: bld_backend
        type: MvnBuild
        configuration:
          sourceLocation: .
          mvnCommand: clean install -ntp
          configFileLocation: .
          configFileName: mvn-art-config
          inputResources:
            - name: incoming
            - name: be_gitRepo
              trigger: true
          integrations:
            - name: Artifactory
          runtime:
            type: image
            image:
              auto:
                language: java

        execution:
          onStart:
            - javac -version
            - mvn --version
 
      - name: publish_app_build
        type: PublishBuildInfo
        configuration:
          forceXrayScan: false
          inputSteps:
            - name: bld_backend
          outputResources:
            - name: appl_build_info
 
      - name: promote_app_build
        type: PromoteBuild
        configuration:
          targetRepository: docker-local
          integrations:
            - name: Artifactory
          inputResources:
            - name: appl_build_info
          outputResources:
            - name: appl_promoted_build_info_1
